(function($){
	$(function(){
		$.fn.zTree.init($("#menu_manage_tree"), {
			async:{
				enable:true,
				url:'sys/findAllMenu.action'
			},
			data:{
				key:{
					name:'menuName'
				},
				simpleData:{
					enable:true,
					idKey:'id',
					pIdKey:'menuParent',
					rootPId:''
				}
			},
			callback:{
				onClick:function(){
					$('#menuListPanel').panel({
						href:'system/menuList.html'
					});
				}
			}
		});
	});
})(jQuery);